apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DenyPodBySubstring
metadata:
  name: pod-name-must-not-contain-given-substring
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    substring: "helloworld"