--- 

apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ForbidRunasRootUser
metadata:
  name: forbidrunasrootuser
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
